name: Test and deploy master branch

on: [push]

jobs:
  test_pkg:
    name: Test Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with coverage
      run: |
        coverage run -m unittest
        coverage report

  deploy_pkg:
    name: Deploy latest tag to pypi
    needs: test_pkg
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip setuptools wheel
        pip install tqdm
        pip install --user --upgrade twine

    - name: Build package
      run: python setup.py bdist_wheel

    - name: Deploy package
      run: python -m twine upload -u "__token__" -p ${{ secrets.PYPI_TOKEN }}  dist/*